// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// printMendelianMatrices
void printMendelianMatrices();
RcppExport SEXP ProgenyArray_printMendelianMatrices() {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        printMendelianMatrices();
    }
    return R_NilValue;
END_RCPP
}
// countGenotypes
IntegerVector countGenotypes(IntegerVector x);
RcppExport SEXP ProgenyArray_countGenotypes(SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP );
        IntegerVector __result = countGenotypes(x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
