// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// inferParents
List inferParents(IntegerMatrix progeny, IntegerMatrix parents, NumericVector freqs, NumericVector ehetv, NumericVector ehomv, LogicalVector verbosev);
RcppExport SEXP ProgenyArray_inferParents(SEXP progenySEXP, SEXP parentsSEXP, SEXP freqsSEXP, SEXP ehetvSEXP, SEXP ehomvSEXP, SEXP verbosevSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerMatrix >::type progeny(progenySEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type parents(parentsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type freqs(freqsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type ehetv(ehetvSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type ehomv(ehomvSEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type verbosev(verbosevSEXP );
        List __result = inferParents(progeny, parents, freqs, ehetv, ehomv, verbosev);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// countGenotypes
IntegerVector countGenotypes(IntegerVector x);
RcppExport SEXP ProgenyArray_countGenotypes(SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP );
        IntegerVector __result = countGenotypes(x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// allele_ll
NumericVector allele_ll(IntegerVector progeny_genos, double ehet, double ehom, double freq, IntegerVector father_genos);
RcppExport SEXP ProgenyArray_allele_ll(SEXP progeny_genosSEXP, SEXP ehetSEXP, SEXP ehomSEXP, SEXP freqSEXP, SEXP father_genosSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type progeny_genos(progeny_genosSEXP );
        Rcpp::traits::input_parameter< double >::type ehet(ehetSEXP );
        Rcpp::traits::input_parameter< double >::type ehom(ehomSEXP );
        Rcpp::traits::input_parameter< double >::type freq(freqSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type father_genos(father_genosSEXP );
        NumericVector __result = allele_ll(progeny_genos, ehet, ehom, freq, father_genos);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
