# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.inferParents <- function(progeny, parents, freqs, ehetv, ehomv, verbosev) {
    .Call('ProgenyArray_inferParents', PACKAGE = 'ProgenyArray', progeny, parents, freqs, ehetv, ehomv, verbosev)
}

countGenotypes <- function(x) {
    .Call('ProgenyArray_countGenotypes', PACKAGE = 'ProgenyArray', x)
}

pa_gp_ext <- function(gp, freq, ehet, ehom) {
    .Call('ProgenyArray_pa_gp_ext', PACKAGE = 'ProgenyArray', gp, freq, ehet, ehom)
}

pg_theta_ext <- function(gp, freq, ehet, ehom) {
    .Call('ProgenyArray_pg_theta_ext', PACKAGE = 'ProgenyArray', gp, freq, ehet, ehom)
}

max_ll_matrix <- function(x, y, which_max) {
    .Call('ProgenyArray_max_ll_matrix', PACKAGE = 'ProgenyArray', x, y, which_max)
}

geno_ll <- function(progeny_genos, father_genos, which_father, freqs, ehet, ehom) {
    .Call('ProgenyArray_geno_ll', PACKAGE = 'ProgenyArray', progeny_genos, father_genos, which_father, freqs, ehet, ehom)
}

