# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.printMendelianMatrices <- function(ehetv, ehomv, log) {
    invisible(.Call('ProgenyArray_printMendelianMatrices', PACKAGE = 'ProgenyArray', ehetv, ehomv, log))
}

.allParentLikelihoods <- function(progeny, parents, freqs, ehetv, ehomv) {
    .Call('ProgenyArray_allParentLikelihoods', PACKAGE = 'ProgenyArray', progeny, parents, freqs, ehetv, ehomv)
}

.inferParents <- function(progeny, parents, freqs, ehetv, ehomv, verbosev) {
    .Call('ProgenyArray_inferParents', PACKAGE = 'ProgenyArray', progeny, parents, freqs, ehetv, ehomv, verbosev)
}

countGenotypes <- function(x) {
    .Call('ProgenyArray_countGenotypes', PACKAGE = 'ProgenyArray', x)
}

