# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.inferParents <- function(progeny, parents, freqs, ehetv, ehomv, verbosev) {
    .Call('ProgenyArray_inferParents', PACKAGE = 'ProgenyArray', progeny, parents, freqs, ehetv, ehomv, verbosev)
}

countGenotypes <- function(x) {
    .Call('ProgenyArray_countGenotypes', PACKAGE = 'ProgenyArray', x)
}

allele_ll <- function(progeny_genos, ehet, ehom, freq, father_genos) {
    .Call('ProgenyArray_allele_ll', PACKAGE = 'ProgenyArray', progeny_genos, ehet, ehom, freq, father_genos)
}

